### ISSUE TITLE
Create job tracker using ActionCable

### ISSUE THREAD

**Issue by oneroyalace** [TechAndCheck/zenodotus#107]
- [x] Create status page for jobs (showing list of jobs in queue)
- [x] Create ActionCable channel
- [x] Update ActionCable channel as the job finishes
- [x] Update DOM with new ActionCable status

**Comment by oneroyalace** [comment]
#110
